const cardSrcMeaning = [ // ["Name","Normal","Reverse"]
    ["The Fool","beginnings, freedom, innocence, originality, adventure, idealism, spontaneity","reckless, careless, distracted, naive, foolish, gullible, stale, dull"],
    ["The Magician","willpower, desire, being resourceful,, skill, ability, concentration, manifestation","manipulation, cunning, trickery, wasted talent, illusion, deception"],
    ["The High Priestess","unconscious, intuition, mystery, spirituality, higher power, inner voice","repressed intuition, hidden motives, superficiality, confusion, cognitive dissonance"],
    ["The Empress","divine feminine, sensuality, fertility, nurturing, creativity, beauty, abundance, nature","insecurity, overbearing, negligence, smothering, lack of growth, lack of progress"],
    ["The Emperor","stability, structure, protection, authority, control, practicality, focus, discipline","tyrant, domineering, rigid, stubborn, lack of discipline, recklessness"],
    ["The Hierophant","tradition, social groups, conventionality, conformity, education, knowledge, beliefs","rebellion, unconventionality, non-conformity, new methods, ignorance"],
    ["The Lovers","love, unions, partnerships, relationships, choices, romance, balance, unity","disharmony, imbalance, conflict, detachment, bad choices, indecision"],
    ["The Chariot","success, ambition, determination, willpower, control, self-discipline, focus","forceful, no direction, no control, powerless, aggression, obstacles"],
    ["Strength","courage, bravery, confidence, compassion, self-confidence, inner power","self-doubt, weakness, low confidence, inadequacy, cowardice, forcefulness"],
    ["The Hermit","self-reflection, introspection, contemplation, withdrawal, solitude, search for self","loneliness, isolation, recluse, being anti-social, rejection, returning to society"],
    ["The Wheel of Fortune","change, cycles, fate, decisive moments, luck, fortune, unexpected events","bad luck, lack of control, clinging to control, unwelcome changes, delays"],
    ["Justice","justice, karma, consequence, accountability, law, truth, honesty, integrity, cause and effect","injustice, retribution, dishonesty, corruption, dishonesty, unfairness, avoiding accountability"],
    ["The Hanged Man","sacrifice, waiting, uncertainty, lack of direction, perspective, contemplation","stalling, disinterest, stagnation, avoiding sacrifice, standstill, apathy"],
    ["Death","transformation, endings, change, transition, letting go, release","fear of change, repeating negative patterns, resisting change, stagnancy, decay"],
    ["Temperance","balance, peace, patience, moderation, calm, tranquillity, harmony, serenity","imbalance, excess, extremes, discord, recklessness, hastiness"],
    ["The Devil","oppression, addiction, obsession, dependency, excess, powerlessness, limitations","independence, freedom, revelation, release, reclaiming power, reclaiming control"],
    ["The Tower","disaster, destruction, upheaval, trauma, sudden change, chaos","averting disaster, delaying the inevitable, resisting change"],
    ["The Star","hope, inspiration, positivity, faith, renewal, healing, rejuvenation","hopelessness, despair, negativity, lack of faith, despondent"],
    ["The Moon","illusion, intuition, uncertainty, confusion, complexity, secrets, unconscious","fear, deception, anxiety, misunderstanding, misinterpretation, clarity, understanding"],
    ["The Sun","happiness, success, optimism, vitality, joy, confidence, happiness, truth","blocked happiness, excessive enthusiasm, pessimism, unrealistic expectations, conceitedness"],
    ["Judgement","self-evaluation, awakening, renewal, purpose, reflection, reckoning","self-doubt, lack of self-awareness, failure to learn lessons, self-loathing"],
    ["The World","completion, achievement, fulfillment, sense of belonging, wholeness, harmony","lack of closure, lack of achievement, feeling incomplete, emptiness"],
    ["2 of Cups","unity, partnership, attraction, connection, close bonds, joining forces, mutual respect","separation, rejection, division, imbalance, tension, bad communication, withdrawal"],
    ["3 of Cups","friendship, community, gatherings, celebrations, group events, social events"," events, social events	gossip, scandal, excess, isolation, loneliness, solitude, imbalanced social life"],
    ["4 of Cups","apathy, contemplation, feeling disconnected, melancholy, boredom, indifference, discontent","clarity, awareness, acceptance, choosing happiness, depression, negativity"],
    ["5 of Cups","loss, grief, disappointment, sadness, mourning, discontent, feeling let down","acceptance, moving on, finding peace, contentment, seeing positives"],
    ["6 of Cups","nostalgia, memories, familiarity, healing, comfort, sentimentality, pleasure","stuck in past, moving forward, leaving home, independence"],
    ["7 of Cups","choices, searching for purpose, illusion, fantasy, daydreaming, wishful thinking, indecision","lack of purpose, disarray, confusion, diversion, distractions, clarity, making choices"],
    ["8 of Cups","abandonment, walking away, letting go, searching for truth, leaving behind","stagnation, monotony, accepting less, avoidance, fear of change, staying in bad situation"],
    ["9 of Cups","wishes coming true, contentment, satisfaction, success, achievements, recognition, pleasure","unhappiness, lack of fulfillment, disappointment, underachievement, arrogance, snobbery"],
    ["10 of Cups","happiness, homecomings, fulfillment, emotional stability, security, domestic harmony","unhappy home, separation, domestic conflict, disharmony, isolation​"],
    ["Ace of Cups","love, new feelings, emotional awakening, creativity, spirituality, intuition","coldness, emptiness, emotional loss, blocked creativity, feeling unloved, gloominess"],
    ["King of Cups","wise, diplomatic, balance between head and heart, devoted, advisor, counsellor","overwhelmed, anxious, cold, repressed, withdrawn, manipulative, selfish"],
    ["Knight of Cups","idealist, charming, artistic, graceful, tactful, diplomatic, mediator, negotiator","disappointment, tantrums, moodiness, turmoil, avoiding conflict, vanity"],
    ["Page of Cups","idealism, sensitivity, dreamer, naivete, innocence, inner child, head in the clouds","emotional vulnerability, immaturity, neglecting inner child, escapism, insecurity"],
    ["Queen of Cups","compassion, warmth, kindness, intuition, healer, counsellor, supportive","insecurity, giving too much, overly-sensitive, needy, fragile, dependence, martyrdom"],
    ["2 of Pentacles","balancing resources, adaptation, resourcefulness, flexibility, stretching resources","imbalance, unorganized, overwhelmed, messiness, chaos, overextending"],
    ["3 of Pentacles","teamwork, shared goals, collaboration, apprenticeship, effort, pooling energy","lack of cohesion, lack of teamwork, apathy, poor motivation, conflict, ego, competition"],
    ["4 of Pentacles","possessiveness, insecurity, hoarding, stinginess, stability, security, savings, materialism, wealth, frugality, boundaries, guardedness","generosity, giving, spending, openness, financial insecurity, reckless spending"],
    ["5 of Pentacles","hardship, loss, isolation, feeling abandoned, adversity, struggle, unemployment, alienation, disgrace","positive changes, recovery from loss, overcoming adversity, forgiveness, feeling welcomed"],
    ["6 of Pentacles","generosity, charity, community, material help, support, sharing, giving and receiving, gratitude","power dynamics, abuse of generosity, strings attached gifts, inequality, extortion"],
    ["7 of Pentacles","harvest, rewards, results, growth, progress, perseverance, patience, planning","unfinished work, procrastination, low effort, waste, lack of growth, setbacks, impatience, lack of reward"],
    ["8 of Pentacles","skill, talent, craftsmanship, quality, high standards, expertise, mastery, commitment, dedication, accomplishment","lack of quality, rushed job, bad reputation, lack of motivation, mediocrity, laziness, low skill, dead-end job"],
    ["9 of Pentacles","rewarded efforts, success, achievement, independence, leisure, material security, self-sufficiency","being guarded, living beyond means, material instability, reckless spending, superficiality"],
    ["10 of Pentacles","legacy, roots, family, ancestry, inheritance, windfall, foundations, privilege, affluence, stability, tradition","family disputes, bankruptcy, debt, fleeting success, conflict over money, instability, breaking traditions"],
    ["Ace of Pentacles","new opportunities, resources, abundance, prosperity, security, stability, manifestation","missed chances, scarcity, deficiency, instability, stinginess, bad investments"],
    ["King of Pentacles","abundance, prosperity, security, ambitious, safe, kind, patriarchal, protective, businessman, provider, sensual, reliable","greed, materialistic, wasteful, chauvinist, poor financial decisions, gambler, exploitative, possessive"],
    ["Knight of Pentacles","practical, reliable, efficient, stoic, slow and steady, hard-working, committed, patient, conservative","workaholic, laziness, dull, boring, no initiative, cheap, irresponsible, gambler, risky investments"],
    ["Page of Pentacles","ambitious, diligent, goal oriented, planner, consistent, star student, studious, grounded, loyal, faithful, dependable","foolish, immature, irresponsible, lazy, underachiever, procrastinator, missed chances, poor prospects"],
    ["Queen of Pentacles","generous, caring, nurturing, homebody, good business sense, practical, comforting, welcoming, sensible, luxurious","selfish, unkempt, jealous, insecure, greedy, materialistic, gold digger, intolerant, self-absorbed, envious"],
    ["2 of Swords","stalemate, difficult choices, stuck in the middle, denial, hidden information","indecision, hesitancy, anxiety, too much information, no right choice, truth revealed"],
    ["3 of Swords","heartbreak, separation, sadness, grief, sorrow, upset, loss, trauma, tears","healing, forgiveness, recovery, reconciliation, repressing emotions"],
    ["4 of Swords","rest, relaxation, peace, sanctuary, recuperation, self-protection, rejuvenation","recovery, awakening, re-entering world, release from isolation, restlessness, burnout"],
    ["5 of Swords","arguments, disputes, aggression, bullying, intimidation, conflict, hostility, stress","reconciliation, resolution, compromise, revenge, regret, remorse, cutting losses"],
    ["6 of Swords","moving on, departure, leaving behind, distance, accepting lessons","stuck in past, returning to trouble, running away from problems, trapped"],
    ["7 of Swords","lies, trickery, scheming, strategy, resourcefulness,sneakiness, cunning","confession, conscience, regret, maliciousness, truth revealed"],
    ["8 of Swords","trapped, restricted, victimized, paralyzed, helpless, powerless, imprisonment","freedom, release, taking control, survivor, facing fears, empowered, surrender"],
    ["9 of Swords","fear, anxiety, negativity, breaking point, despair, nightmares, isolation","recovery, learning to cope, facing life, finding help, shame, guilt, mental health issues"],
    ["10 of Swords","ruin, failure, bitterness, collapse, exhaustion, dead end, victimization, betrayal","survival, improvement, healing, lessons learned, despair, relapse"],
    ["Ace of Swords","clarity, breakthrough, new idea, concentration, vision, force, focus, truth","confusion, miscommunication, hostility, arguments, destruction, brutality"],
    ["King of Swords","reason, authority, discipline, integrity, morality, serious, high standards, strict","irrational, dictator, oppressive, inhumane, controlling, cold, ruthless, dishonest"],
    ["Knight of Swords","assertive, direct, impatient, intellectual, daring, focused, perfectionist, ambitious","rude, tactless, forceful, bully, aggressive, vicious, ruthless, arrogant"],
    ["Page of Swords","curious, witty, chatty, communicative, inspired, vigilant, alert, mental agility","scatterbrained, cynical, sarcastic, gossipy, insulting, rude, lack of planning"],
    ["Queen of Swords","honest, independent, principled, fair, constructive criticism, objective, perceptive","pessimistic, malicious, manipulative, harsh, bitter, spiteful, cruel, deceitful, unforgiving"],
    ["2 of Wands","planning, first steps, making decisions, leaving comfort, taking risks","bad planning, overanalyzing, not taking action, playing it safe, avoiding risk"],
    ["3 of Wands","momentum, confidence, expansion, growth, foresight, looking ahead","restriction, limitations, lack of progress, obstacles, delays, frustration"],
    ["4 of Wands","community, home, celebrations, reunions, parties, gatherings, stability, belonging","lack of support, instability, feeling unwelcome, transience, lack of roots, home conflict"],
    ["5 of Wands","conflict, competition, arguments, aggression, tension, rivals, clashes of ego","end of conflict, cooperation, agreements, truces, harmony, peace, avoiding conflict"],
    ["6 of Wands","success, victory, triumph, rewards, recognition, praise, acclaim, pride","failure, lack of recognition, no rewards, lack of achievement"],
    ["7 of Wands","protectiveness, standing up for yourself, defending yourself, protecting territory","giving up, admitting defeat, yielding, lack of self belief, surrender"],
    ["8 of Wands","movement, speed, progress, quick decisions, sudden changes, excitement","waiting, slowness, chaos, delays, losing momentum, hastiness, being unprepared"],
    ["9 of Wands","last stand, persistence, grit, resilience, perseverance, close to success, fatigue","stubbornness, rigidity, defensiveness, refusing compromise, giving up"],
    ["10 of Wands","burden, responsibility, duty, stress, obligation, burning out, struggles","failure to delegate, shouldering too much responsibility, collapse, breakdown"],
    ["Ace of Wands","inspiration, creative spark, new initiative, new passion, enthusiasm, energy","delays, blocks, lack of passion, lack of energy, hesitancy, creative blocks"],
    ["King of Wands","leadership, vision, big picture, taking control, daring decisions, boldness, optimism","forceful, domineering, tyrant, vicious, powerless, ineffective, weak leader"],
    ["Knight of Wands","courageous, energetic, charming, hero, rebellious, hot tempered, free spirit","arrogant, reckless, impatient, lack of self control, passive, volatile, domineering"],
    ["Page of Wands","adventure, excitement, fresh ideas, cheerfulness, energetic, fearless, extroverted","hasty, impatient, lacking ideas, tantrums, laziness, boring, unreliable, distracted"],
    ["Queen of Wands","confident, self-assured, passionate, determined, social, charismatic, vivacious, optimistic","demanding, vengeful, low confidence, jealous, selfish, temperamental, bully"]
];//from https://labyrinthos.co/blogs/tarot-card-meanings-list?srsltid=AfmBOooFFIeOodu6mhUcIJc2Zm325VNy1STnItCWKDbeY_7uNnMZ5Lxu